# Generated by Django 3.2.19 on 2023-08-09 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psat', '0002_problemmemo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problemmemo',
            unique_together={('user', 'problem')},
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(db_column='problem_id', on_delete=django.db.models.deletion.CASCADE, to='psat.problem', verbose_name='문제 ID')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자 ID')),
            ],
            options={
                'verbose_name': 'tagged problem',
                'verbose_name_plural': 'tagged problems',
                'unique_together': {('user', 'problem')},
            },
        ),
    ]
