# Generated by Django 4.2.4 on 2023-09-10 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psat', '0005_remove_problem_tags_alter_evaluation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='exam',
            field=models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='psat.exam'),
        ),
    ]
