# Generated by Django 4.2.5 on 2023-09-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psat', '0007_alter_exam_ex_alter_exam_sub_alter_exam_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.IntegerField(choices=[(1, '①'), (2, '②'), (3, '③'), (4, '④'), (5, '⑤')]),
        ),
    ]
