# Generated by Django 4.2.5 on 2023-10-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psat', '0010_alter_like_options_alter_likelog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='open',
            name='session_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
