# Generated by Django 4.2.5 on 2023-10-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psat', '0011_open_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='open',
            old_name='session_key',
            new_name='ip_address',
        ),
        migrations.AlterField(
            model_name='open',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
