# Generated by Django 5.0.1 on 2024-02-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psat', '0014_remove_comment_content_remove_memo_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.TextField(default='no_title', max_length=100),
            preserve_default=False,
        ),
    ]
