# Generated by Django 5.0.3 on 2024-04-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psat', '0016_collection_collectionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='open',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='solve',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
