# Generated by Django 5.2.4 on 2025-08-12 06:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('purple', 'Purple')], max_length=10, verbose_name='색깔')),
                ('shape', models.CharField(choices=[('oval', 'Oval'), ('squiggle', 'Squiggle'), ('diamond', 'Diamond')], max_length=10, verbose_name='모양')),
                ('count', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], verbose_name='개수')),
                ('fill', models.CharField(choices=[('open', 'Open'), ('striped', 'Striped'), ('solid', 'Solid')], max_length=10, verbose_name='무늬')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='세션 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='시작 시각')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시각')),
                ('total_time', models.FloatField(default=0.0, verbose_name='총 게임 시간')),
                ('finished', models.BooleanField(default=False, verbose_name='종료 여부')),
                ('score', models.IntegerField(default=0, verbose_name='점수')),
                ('set_attempts', models.IntegerField(default=0, verbose_name='세트 시도 횟수')),
                ('hint_requests', models.IntegerField(default=0, verbose_name='힌트 요청 횟수')),
                ('success_count', models.IntegerField(default=0, verbose_name='성공 횟수')),
                ('failure_count', models.IntegerField(default=0, verbose_name='실패 횟수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardgame_set_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False, verbose_name='사용 완료')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='사용 시각')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_boardgame_set.card')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_boardgame_set.session')),
            ],
            options={
                'db_table': 'a_boardgame_set_session_card',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='기록 시각')),
                ('event_type', models.CharField(max_length=32, verbose_name='이벤트 종류')),
                ('detail', models.JSONField(default=dict, verbose_name='세부 내용')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_boardgame_set.session')),
            ],
            options={
                'db_table': 'a_boardgame_set_session_event',
                'ordering': ['timestamp'],
            },
        ),
    ]
