# Generated by Django 5.1 on 2024-09-24 06:08

import a_psat.models.lecture_models
import a_psat.models.problem_models
import ckeditor.fields
import ckeditor_uploader.fields
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=a_psat.models.lecture_models.subject_choice, default='언어', max_length=2)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube_id', models.CharField(blank=True, max_length=20, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('order', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '강의',
                'verbose_name_plural': '강의',
                'db_table': 'a_psat_lecture',
                'ordering': ['subject', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LectureTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '강의 태그',
                'verbose_name_plural': '강의 태그',
                'db_table': 'a_psat_lecture_tag',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=a_psat.models.problem_models.year_choice, default=2024)),
                ('exam', models.CharField(choices=[('행시', '5급공채/행정고시'), ('입시', '입법고시'), ('칠급', '7급공채'), ('칠예', '7급공채 예시'), ('민경', '민간경력'), ('외시', '외교원/외무고시'), ('견습', '견습')], default='행시', max_length=2)),
                ('subject', models.CharField(choices=[('헌법', '헌법'), ('언어', '언어논리'), ('자료', '자료해석'), ('상황', '상황판단')], default='언어', max_length=2)),
                ('paper_type', models.CharField(default='', max_length=2)),
                ('number', models.IntegerField(choices=a_psat.models.problem_models.number_choice, default=1)),
                ('answer', models.IntegerField(choices=a_psat.models.problem_models.answer_choice, default=1)),
                ('question', models.TextField()),
                ('data', models.TextField()),
            ],
            options={
                'verbose_name': '01_문제',
                'verbose_name_plural': '01_문제',
                'ordering': ['-year', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '07_태그',
                'verbose_name_plural': '07_태그',
                'db_table': 'a_psat_problem_tag',
            },
        ),
        migrations.CreateModel(
            name='LectureComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('hit', models.IntegerField(default=1, verbose_name='조회수')),
                ('is_active', models.BooleanField(default=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='a_psat.lecture')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comments', to='a_psat.lecturecomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psat_lecture_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'a_psat_lecture_comment',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LectureOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opens', to='a_psat.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psat_lecture_opens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '강의 확인기록',
                'verbose_name_plural': '강의 확인기록',
                'db_table': 'a_psat_lecture_open',
            },
        ),
        migrations.CreateModel(
            name='ProblemCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psat_problem_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '09_컬렉션',
                'verbose_name_plural': '09_컬렉션',
                'db_table': 'a_psat_problem_collection',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProblemCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='a_psat.problemcollection')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_problems', to='a_psat.problem')),
            ],
            options={
                'verbose_name': '10_컬렉션 문제',
                'verbose_name_plural': '10_컬렉션 문제',
                'db_table': 'a_psat_problem_collection_item',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='collections',
            field=models.ManyToManyField(related_name='collected_psat_problems', through='a_psat.ProblemCollectionItem', to='a_psat.problemcollection'),
        ),
        migrations.CreateModel(
            name='ProblemComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('hit', models.IntegerField(default=1, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comments', to='a_psat.problemcomment')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='a_psat.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psat_problem_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'a_psat_problem_comment',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='comment_users',
            field=models.ManyToManyField(related_name='commented_psat_problems', through='a_psat.ProblemComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProblemCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='a_psat.problemcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psat_problem_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'a_psat_problem_comment_like',
            },
        ),
        migrations.AddField(
            model_name='problemcomment',
            name='like_users',
            field=models.ManyToManyField(related_name='liked_psat_problem_comments', through='a_psat.ProblemCommentLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProblemLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_liked', models.BooleanField(default=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='a_psat.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psat_problem_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '03_즐겨찾기',
                'verbose_name_plural': '03_즐겨찾기',
                'db_table': 'a_psat_problem_like',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='like_users',
            field=models.ManyToManyField(related_name='liked_psat_problems', through='a_psat.ProblemLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProblemMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='a_psat.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psat_problem_memos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '06_메모',
                'verbose_name_plural': '06_메모',
                'db_table': 'a_psat_problem_memo',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='memo_users',
            field=models.ManyToManyField(related_name='memoed_psat_problems', through='a_psat.ProblemMemo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProblemOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_psat.problem')),
            ],
            options={
                'verbose_name': '02_확인기록',
                'verbose_name_plural': '02_확인기록',
                'db_table': 'a_psat_problem_open',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProblemRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.IntegerField(choices=[(1, '⭐️'), (2, '⭐️⭐️'), (3, '⭐️⭐️⭐️'), (4, '⭐️⭐️⭐️⭐️'), (5, '⭐️⭐️⭐️⭐️⭐️')])),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='a_psat.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psat_problem_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '04_난이도',
                'verbose_name_plural': '04_난이도',
                'db_table': 'a_psat_problem_rate',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='rate_users',
            field=models.ManyToManyField(related_name='rated_psat_problems', through='a_psat.ProblemRate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProblemSolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('answer', models.IntegerField(choices=[(1, '①'), (2, '②'), (3, '③'), (4, '④'), (5, '⑤')])),
                ('is_correct', models.BooleanField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='a_psat.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psat_problem_solves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '05_정답확인',
                'verbose_name_plural': '05_정답확인',
                'db_table': 'a_psat_problem_solve',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='solve_users',
            field=models.ManyToManyField(related_name='solved_psat_problems', through='a_psat.ProblemSolve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProblemTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_problems', to='a_psat.problem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='a_psat.problemtag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psat_tagged_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '08_태그 문제',
                'verbose_name_plural': '08_태그 문제',
                'db_table': 'a_psat_problem_tagged_item',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='a_psat.ProblemTaggedItem', to='a_psat.ProblemTag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='LectureLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='a_psat.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psat_lecture_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'a_psat_lecture_like',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'lecture'), name='unique_psat_lecture_like')],
                'unique_together': {('user', 'lecture')},
            },
        ),
        migrations.CreateModel(
            name='LectureMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='a_psat.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_memos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'a_psat_lecture_memo',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'lecture'), name='unique_psat_lecture_memo')],
            },
        ),
        migrations.CreateModel(
            name='LectureTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_lectures', to='a_psat.lecture')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='a_psat.lecturetag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psat_tagged_lectures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '태그된 강의',
                'verbose_name_plural': '태그된 강의',
                'db_table': 'a_psat_lecture_tagged_item',
                'constraints': [models.UniqueConstraint(fields=('tag', 'content_object', 'user'), name='unique_psat_lecture_tagged_item')],
            },
        ),
    ]
