# Generated by Django 5.0.3 on 2024-08-09 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemcollectionitem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_problems', to='a_psat.problem'),
        ),
        migrations.AlterField(
            model_name='problemcomment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='a_psat.problem'),
        ),
        migrations.AlterField(
            model_name='problemcommentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='a_psat.problemcomment'),
        ),
        migrations.AlterField(
            model_name='problemlike',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='a_psat.problem'),
        ),
        migrations.AlterField(
            model_name='problemmemo',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='a_psat.problem'),
        ),
        migrations.AlterField(
            model_name='problemrate',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='a_psat.problem'),
        ),
        migrations.AlterField(
            model_name='problemsolve',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='a_psat.problem'),
        ),
    ]
