# Generated by Django 5.0.3 on 2024-08-10 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0002_alter_problemcollectionitem_problem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtaggeditem',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_problems', to='a_psat.problem'),
        ),
        migrations.AlterField(
            model_name='problemtaggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='a_psat.problemtag'),
        ),
        migrations.AlterField(
            model_name='problemtaggeditem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psat_tagged_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
