# Generated by Django 5.1 on 2024-10-23 12:43

import a_psat.models.choices
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0002_alter_problem_answer_alter_problem_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='psat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='psats', to='a_psat.psat', verbose_name='PSAT'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='exam',
            field=models.CharField(choices=a_psat.models.choices.exam_choice, default='행시', max_length=2, verbose_name='시험'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='subject',
            field=models.CharField(choices=a_psat.models.choices.subject_choice, default='언어', max_length=2, verbose_name='과목'),
        ),
    ]
