# Generated by Django 5.1 on 2024-10-24 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0003_problem_psat_alter_problem_exam_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['psat', 'id'], 'verbose_name': '01_문제', 'verbose_name_plural': '01_문제'},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='year',
        ),
        migrations.AlterField(
            model_name='problem',
            name='data',
            field=models.TextField(default='', verbose_name='자료'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='psat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='a_psat.psat', verbose_name='PSAT'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='question',
            field=models.TextField(default='', verbose_name='발문'),
        ),
    ]
