# Generated by Django 5.1 on 2024-10-24 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0004_alter_problem_options_remove_problem_exam_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='problem',
            constraint=models.UniqueConstraint(fields=('psat', 'subject', 'number'), name='unique_problem'),
        ),
    ]
