# Generated by Django 5.1 on 2024-09-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0005_lecture_lecturetag_alter_problem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='open_users',
        ),
        migrations.RemoveField(
            model_name='problemopen',
            name='user',
        ),
        migrations.AddField(
            model_name='problemopen',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
