# Generated by Django 5.1 on 2024-10-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0005_problem_unique_problem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['subject', 'order'], 'verbose_name': '[온라인강의] 01_강의', 'verbose_name_plural': '[온라인강의] 01_강의'},
        ),
        migrations.AlterModelOptions(
            name='lecturelike',
            options={'ordering': ['-id'], 'verbose_name': '[온라인강의] 03_즐겨찾기', 'verbose_name_plural': '[온라인강의] 03_즐겨찾기'},
        ),
        migrations.AlterModelOptions(
            name='lecturememo',
            options={'ordering': ['-id'], 'verbose_name': '[온라인강의] 04_메모', 'verbose_name_plural': '[온라인강의] 04_메모'},
        ),
        migrations.AlterModelOptions(
            name='lectureopen',
            options={'verbose_name': '[온라인강의] 02_확인기록', 'verbose_name_plural': '[온라인강의] 02_확인기록'},
        ),
        migrations.AlterModelOptions(
            name='lecturetag',
            options={'verbose_name': '[온라인강의] 05_태그', 'verbose_name_plural': '[온라인강의] 05_태그'},
        ),
        migrations.AlterModelOptions(
            name='lecturetaggeditem',
            options={'verbose_name': '[온라인강의] 06_태그된 강의', 'verbose_name_plural': '[온라인강의] 06_태그된 강의'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['psat', 'id'], 'verbose_name': '[기출문제] 01_문제', 'verbose_name_plural': '[기출문제] 01_문제'},
        ),
        migrations.AlterModelOptions(
            name='problemcollection',
            options={'ordering': ['-id'], 'verbose_name': '[기출문제] 09_컬렉션', 'verbose_name_plural': '[기출문제] 09_컬렉션'},
        ),
        migrations.AlterModelOptions(
            name='problemcollectionitem',
            options={'ordering': ['-id'], 'verbose_name': '[기출문제] 10_컬렉션 문제', 'verbose_name_plural': '[기출문제] 10_컬렉션 문제'},
        ),
        migrations.AlterModelOptions(
            name='problemlike',
            options={'ordering': ['-id'], 'verbose_name': '[기출문제] 03_즐겨찾기', 'verbose_name_plural': '[기출문제] 03_즐겨찾기'},
        ),
        migrations.AlterModelOptions(
            name='problemmemo',
            options={'ordering': ['-id'], 'verbose_name': '[기출문제] 06_메모', 'verbose_name_plural': '[기출문제] 06_메모'},
        ),
        migrations.AlterModelOptions(
            name='problemopen',
            options={'ordering': ['-id'], 'verbose_name': '[기출문제] 02_확인기록', 'verbose_name_plural': '[기출문제] 02_확인기록'},
        ),
        migrations.AlterModelOptions(
            name='problemrate',
            options={'ordering': ['-id'], 'verbose_name': '[기출문제] 04_난이도', 'verbose_name_plural': '[기출문제] 04_난이도'},
        ),
        migrations.AlterModelOptions(
            name='problemsolve',
            options={'ordering': ['-id'], 'verbose_name': '[기출문제] 05_정답확인', 'verbose_name_plural': '[기출문제] 05_정답확인'},
        ),
        migrations.AlterModelOptions(
            name='problemtag',
            options={'verbose_name': '[기출문제] 07_태그', 'verbose_name_plural': '[기출문제] 07_태그'},
        ),
        migrations.AlterModelOptions(
            name='problemtaggeditem',
            options={'ordering': ['-id'], 'verbose_name': '[기출문제] 08_태그된 문제', 'verbose_name_plural': '[기출문제] 08_태그된 문제'},
        ),
        migrations.AlterModelOptions(
            name='psat',
            options={'ordering': ['-year', 'order'], 'verbose_name': '[기출문제] 00_PSAT', 'verbose_name_plural': '[기출문제] 00_PSAT'},
        ),
        migrations.AlterUniqueTogether(
            name='lecturelike',
            unique_together=set(),
        ),
    ]
