# Generated by Django 5.1 on 2024-09-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0006_remove_problem_open_users_remove_problemopen_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problemlike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='problemmemo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='problemrate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='problemsolve',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='problemlike',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='problemmemo',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='problemrate',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='problemsolve',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='problemlike',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='problemmemo',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='problemrate',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='problemsolve',
            name='remarks',
        ),
    ]
