# Generated by Django 5.1 on 2024-09-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0007_alter_problemlike_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemcollection',
            options={'ordering': ['-id'], 'verbose_name': '09_컬렉션', 'verbose_name_plural': '09_컬렉션'},
        ),
        migrations.AlterModelOptions(
            name='problemcollectionitem',
            options={'ordering': ['-id'], 'verbose_name': '10_컬렉션 문제', 'verbose_name_plural': '10_컬렉션 문제'},
        ),
        migrations.RenameField(
            model_name='problemlike',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='problemmemo',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='problemrate',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='problemsolve',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='problemtaggeditem',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AlterUniqueTogether(
            name='problemcollection',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='problemcollectionitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='problemcollection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='problemcollectionitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
