# Generated by Django 5.1 on 2025-02-03 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0008_predictanswercountlowrank_predictanswercountmidrank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictlocation',
            name='psat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='a_psat.psat'),
        ),
        migrations.AlterField(
            model_name='predictstatistics',
            name='psat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_statistics', to='a_psat.psat'),
        ),
        migrations.AlterField(
            model_name='predictstudent',
            name='psat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_students', to='a_psat.psat'),
        ),
    ]
