# Generated by Django 5.1 on 2024-09-14 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0008_alter_problemcollection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemtaggeditem',
            options={'ordering': ['-id'], 'verbose_name': '08_태그 문제', 'verbose_name_plural': '08_태그 문제'},
        ),
        migrations.AlterUniqueTogether(
            name='problemtaggeditem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='problemtaggeditem',
            name='remarks',
        ),
    ]
