# Generated by Django 5.1 on 2024-09-14 09:41

import a_psat.models.problem_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0009_alter_problemtaggeditem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.IntegerField(choices=a_psat.models.problem_models.answer_choice, default=1),
        ),
    ]
