# Generated by Django 5.1 on 2024-09-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0010_alter_problem_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='paper_type',
            field=models.CharField(default='', max_length=2),
        ),
    ]
