# Generated by Django 5.1 on 2025-02-19 06:57

import a_psat.models.abstract_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0011_alter_studyanswer_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='등수')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='점수')),
            ],
            options={
                'verbose_name': '[스터디] 08_성적',
                'verbose_name_plural': '[스터디] 08_성적',
                'db_table': 'a_psat_study_result',
                'ordering': ['student'],
            },
        ),
        migrations.RemoveField(
            model_name='studyrank',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studyscore',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studystatistics',
            name='psat',
        ),
        migrations.AlterModelOptions(
            name='studyanswer',
            options={'ordering': ['student', 'problem'], 'verbose_name': '[스터디] 06_답안', 'verbose_name_plural': '[스터디] 06_답안'},
        ),
        migrations.AlterModelOptions(
            name='studyanswercount',
            options={'ordering': ['problem'], 'verbose_name': '[스터디] 07_답안 개수', 'verbose_name_plural': '[스터디] 07_답안 개수'},
        ),
        migrations.AlterModelOptions(
            name='studyanswercountlowrank',
            options={'ordering': ['problem'], 'verbose_name': '[스터디] 11_답안 개수(하위권)', 'verbose_name_plural': '[스터디] 11_답안 개수(하위권)'},
        ),
        migrations.AlterModelOptions(
            name='studyanswercountmidrank',
            options={'ordering': ['problem'], 'verbose_name': '[스터디] 10_답안 개수(중위권)', 'verbose_name_plural': '[스터디] 10_답안 개수(중위권)'},
        ),
        migrations.AlterModelOptions(
            name='studyanswercounttoprank',
            options={'ordering': ['problem'], 'verbose_name': '[스터디] 09_답안 개수(상위권)', 'verbose_name_plural': '[스터디] 09_답안 개수(상위권)'},
        ),
        migrations.AlterModelOptions(
            name='studycategory',
            options={'ordering': ['-id'], 'verbose_name': '[스터디] 00_카테고리', 'verbose_name_plural': '[스터디] 00_카테고리'},
        ),
        migrations.AlterModelOptions(
            name='studycurriculum',
            options={'ordering': ['-id'], 'verbose_name': '[스터디] 04_커리큘럼', 'verbose_name_plural': '[스터디] 04_커리큘럼'},
        ),
        migrations.AlterModelOptions(
            name='studyorganization',
            options={'ordering': ['id'], 'verbose_name': '[스터디] 03_교육기관', 'verbose_name_plural': '[스터디] 03_교육기관'},
        ),
        migrations.AlterModelOptions(
            name='studypsat',
            options={'ordering': ['category', 'round'], 'verbose_name': '[스터디] 01_PSAT', 'verbose_name_plural': '[스터디] 01_PSAT'},
        ),
        migrations.AlterModelOptions(
            name='studystudent',
            options={'verbose_name': '[스터디] 05_학생', 'verbose_name_plural': '[스터디] 05_학생'},
        ),
        migrations.AddField(
            model_name='studycategory',
            name='participants',
            field=models.PositiveIntegerField(default=1, verbose_name='참여자 수'),
        ),
        migrations.AddField(
            model_name='studycategory',
            name='round',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='회차 수'),
        ),
        migrations.AddField(
            model_name='studycurriculum',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='커리큘럼명'),
        ),
        migrations.AddField(
            model_name='studypsat',
            name='problem_counts',
            field=models.JSONField(default=a_psat.models.abstract_models.get_default_problem_counts, verbose_name='문제 수'),
        ),
        migrations.AddField(
            model_name='studypsat',
            name='statistics',
            field=models.JSONField(default=a_psat.models.abstract_models.get_default_statistics, verbose_name='통계'),
        ),
        migrations.AddField(
            model_name='studystudent',
            name='rank_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='등수'),
        ),
        migrations.AddField(
            model_name='studystudent',
            name='score_total',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='총점'),
        ),
        migrations.AlterField(
            model_name='studyanswer',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='a_psat.studyproblem'),
        ),
        migrations.AlterField(
            model_name='studyanswercount',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_count', to='a_psat.studyproblem'),
        ),
        migrations.AlterField(
            model_name='studyanswercountlowrank',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_count_low_rank', to='a_psat.studyproblem'),
        ),
        migrations.AlterField(
            model_name='studyanswercountmidrank',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_count_mid_rank', to='a_psat.studyproblem'),
        ),
        migrations.AlterField(
            model_name='studyanswercounttoprank',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_count_top_rank', to='a_psat.studyproblem'),
        ),
        migrations.AlterField(
            model_name='studystudent',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='이름'),
        ),
        migrations.AddConstraint(
            model_name='studyorganization',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_psat_study_organization'),
        ),
        migrations.AddConstraint(
            model_name='studystudent',
            constraint=models.UniqueConstraint(fields=('curriculum', 'serial'), name='unique_psat_study_student'),
        ),
        migrations.AddField(
            model_name='studyresult',
            name='psat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='a_psat.studypsat'),
        ),
        migrations.AddField(
            model_name='studyresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='a_psat.studystudent'),
        ),
        migrations.DeleteModel(
            name='StudyRank',
        ),
        migrations.DeleteModel(
            name='StudyScore',
        ),
        migrations.DeleteModel(
            name='StudyStatistics',
        ),
        migrations.AddConstraint(
            model_name='studyresult',
            constraint=models.UniqueConstraint(fields=('student', 'psat'), name='unique_psat_study_result'),
        ),
    ]
