# Generated by Django 5.1 on 2025-02-21 07:58

import a_psat.models.choices
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0012_studyresult_remove_studyrank_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyanswer',
            options={'ordering': ['student', 'problem'], 'verbose_name': '[스터디] 07_답안', 'verbose_name_plural': '[스터디] 07_답안'},
        ),
        migrations.AlterModelOptions(
            name='studyanswercount',
            options={'ordering': ['problem'], 'verbose_name': '[스터디] 08_답안 개수', 'verbose_name_plural': '[스터디] 08_답안 개수'},
        ),
        migrations.AlterModelOptions(
            name='studyanswercountlowrank',
            options={'ordering': ['problem'], 'verbose_name': '[스터디] 12_답안 개수(하위권)', 'verbose_name_plural': '[스터디] 12_답안 개수(하위권)'},
        ),
        migrations.AlterModelOptions(
            name='studyanswercountmidrank',
            options={'ordering': ['problem'], 'verbose_name': '[스터디] 11_답안 개수(중위권)', 'verbose_name_plural': '[스터디] 11_답안 개수(중위권)'},
        ),
        migrations.AlterModelOptions(
            name='studyanswercounttoprank',
            options={'ordering': ['problem'], 'verbose_name': '[스터디] 10_답안 개수(상위권)', 'verbose_name_plural': '[스터디] 10_답안 개수(상위권)'},
        ),
        migrations.AlterModelOptions(
            name='studyresult',
            options={'ordering': ['student'], 'verbose_name': '[스터디] 09_성적', 'verbose_name_plural': '[스터디] 09_성적'},
        ),
        migrations.AlterModelOptions(
            name='studystudent',
            options={'verbose_name': '[스터디] 06_학생', 'verbose_name_plural': '[스터디] 06_학생'},
        ),
        migrations.AlterField(
            model_name='studyresult',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='점수'),
        ),
        migrations.CreateModel(
            name='StudyCurriculumSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_number', models.PositiveSmallIntegerField(default=1, verbose_name='강의 주차')),
                ('lecture_theme', models.IntegerField(choices=a_psat.models.choices.study_lecture_theme, default=1, verbose_name='강의 주제')),
                ('lecture_round', models.PositiveSmallIntegerField(blank=True, choices=a_psat.models.choices.study_round_choice, null=True, verbose_name='미니테스트 강의 회차')),
                ('homework_round', models.PositiveSmallIntegerField(blank=True, choices=a_psat.models.choices.study_round_choice, null=True, verbose_name='미니테스트 과제 회차')),
                ('lecture_open_datetime', models.DateTimeField(blank=True, null=True, verbose_name='공개 날짜')),
                ('homework_end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='과제 마감 날짜')),
                ('lecture_datetime', models.DateTimeField(blank=True, null=True, verbose_name='강의 날짜')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='a_psat.studycurriculum')),
            ],
            options={
                'verbose_name': '[스터디] 05_커리큘럼 스케줄',
                'verbose_name_plural': '[스터디] 05_커리큘럼 스케줄',
                'db_table': 'a_psat_study_curriculum_schedule',
                'constraints': [models.UniqueConstraint(fields=('curriculum', 'lecture_number'), name='unique_psat_study_curriculum_schedule')],
            },
        ),
    ]
