# Generated by Django 5.1 on 2025-02-26 04:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0013_alter_studyanswer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='predictstudent',
            name='unique_psat_predict_student',
        ),
        migrations.AddConstraint(
            model_name='predictstudent',
            constraint=models.UniqueConstraint(fields=('psat', 'user'), name='unique_psat_predict_student'),
        ),
    ]
