# Generated by Django 5.1 on 2025-02-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0014_remove_predictstudent_unique_psat_predict_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictpsat',
            options={'ordering': ['-id'], 'verbose_name': '[합격예측] 00_PSAT', 'verbose_name_plural': '[합격예측] 00_PSAT'},
        ),
        migrations.AddField(
            model_name='predictstudent',
            name='prime_id',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='프라임법학원 ID'),
        ),
    ]
