# Generated by Django 5.1 on 2025-03-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0015_alter_predictpsat_options_predictstudent_prime_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studystudent',
            name='score_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='총점'),
        ),
    ]
