# Generated by Django 5.1 on 2025-03-18 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0016_alter_studystudent_score_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyanswer',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='a_psat.studyproblem', verbose_name='스터디 문제'),
        ),
        migrations.AlterField(
            model_name='studyanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='a_psat.studystudent', verbose_name='학생'),
        ),
        migrations.AlterField(
            model_name='studycurriculum',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='a_psat.studycategory', verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='studycurriculum',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='a_psat.studyorganization', verbose_name='교육기관'),
        ),
        migrations.AlterField(
            model_name='studycurriculumschedule',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='a_psat.studycurriculum', verbose_name='커리큘럼'),
        ),
        migrations.AlterField(
            model_name='studyproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_problems', to='a_psat.problem', verbose_name='스터디 문제'),
        ),
        migrations.AlterField(
            model_name='studyproblem',
            name='psat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='a_psat.studypsat', verbose_name='PSAT'),
        ),
        migrations.AlterField(
            model_name='studypsat',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psats', to='a_psat.studycategory', verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='studyresult',
            name='psat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='a_psat.studypsat', verbose_name='PSAT'),
        ),
        migrations.AlterField(
            model_name='studyresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='a_psat.studystudent', verbose_name='학생'),
        ),
        migrations.AlterField(
            model_name='studystudent',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='a_psat.studycurriculum', verbose_name='커리큘럼'),
        ),
        migrations.AlterField(
            model_name='studystudent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psat_study_students', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
