# Generated by Django 5.2 on 2025-06-15 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0017_alter_studyanswer_problem_alter_studyanswer_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotate_type', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='annotations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='a_psat.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psat_problem_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'a_psat_problem_annotation',
                'ordering': ['-id'],
            },
        ),
    ]
