# Generated by Django 5.0.3 on 2024-07-10 04:24

import a_predict.models.base_settings
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsatAnswerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('round', models.IntegerField(default=0, verbose_name='회차')),
                ('number', models.IntegerField(choices=a_predict.models.base_settings.ChoiceMethod.number_choices, default=1, verbose_name='번호')),
                ('answer', models.IntegerField(default=0, verbose_name='공식정답')),
                ('count_1', models.IntegerField(default=0, verbose_name='①')),
                ('count_2', models.IntegerField(default=0, verbose_name='②')),
                ('count_3', models.IntegerField(default=0, verbose_name='③')),
                ('count_4', models.IntegerField(default=0, verbose_name='④')),
                ('count_5', models.IntegerField(default=0, verbose_name='⑤')),
                ('count_0', models.IntegerField(default=0, verbose_name='미표기')),
                ('count_multiple', models.IntegerField(default=0, verbose_name='중복 표기')),
                ('count_total', models.IntegerField(default=0, verbose_name='전체')),
                ('year', models.IntegerField(choices=a_predict.models.base_settings.ChoiceMethod.year_choices, default=2024, verbose_name='연도')),
                ('exam', models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.prime_psat_exam_choices, default='행시', max_length=2, verbose_name='시험')),
                ('subject', models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.psat_subject_choices, default='heonbeob', max_length=20, verbose_name='과목')),
            ],
            options={
                'verbose_name': 'PSAT 성적예측 [6] 답안개수',
                'verbose_name_plural': 'PSAT 성적예측 [6] 답안개수',
                'db_table': 'a_predict_psat_answer_count',
            },
            bases=(models.Model, a_predict.models.base_settings.ChoiceMethod),
        ),
        migrations.CreateModel(
            name='PsatDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='주석')),
                ('name', models.CharField(max_length=40, verbose_name='직렬')),
                ('order', models.IntegerField()),
                ('exam', models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.prime_psat_exam_choices, default='행시', max_length=2, verbose_name='시험')),
                ('unit', models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.prime_psat_unit_choices, default='5급공채', max_length=20, verbose_name='모집단위')),
            ],
            options={
                'verbose_name': 'PSAT 성적예측 [3] 직렬',
                'verbose_name_plural': 'PSAT 성적예측 [3] 직렬',
                'db_table': 'a_predict_psat_department',
            },
        ),
        migrations.CreateModel(
            name='PsatExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=0, verbose_name='회차')),
                ('answer_official', models.JSONField(default=dict)),
                ('page_opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam_finished_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer_predict_opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer_official_opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.IntegerField(choices=a_predict.models.base_settings.ChoiceMethod.year_choices, default=2024, verbose_name='연도')),
                ('exam', models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.prime_psat_exam_choices, default='행시', max_length=2, verbose_name='시험')),
            ],
            options={
                'verbose_name': 'PSAT 성적예측 [1] 시험',
                'verbose_name_plural': 'PSAT 성적예측 [1] 시험',
                'db_table': 'a_predict_psat_exam',
            },
        ),
        migrations.CreateModel(
            name='PsatLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('year', models.IntegerField()),
                ('exam', models.CharField(max_length=2, verbose_name='시험')),
                ('round', models.IntegerField(default=0, verbose_name='회차')),
                ('serial_start', models.IntegerField(verbose_name='시작 수험번호')),
                ('serial_end', models.IntegerField(verbose_name='마지막 수험번호')),
                ('region', models.CharField(max_length=10, verbose_name='지역')),
                ('department', models.CharField(max_length=128, verbose_name='직렬')),
                ('school', models.CharField(max_length=30, verbose_name='학교명')),
                ('address', models.CharField(max_length=50, verbose_name='주소')),
                ('contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='연락처')),
            ],
            options={
                'verbose_name': 'PSAT 성적예측 [7] 시험장소',
                'verbose_name_plural': 'PSAT 성적예측 [7] 시험장소',
                'db_table': 'a_predict_psat_location',
            },
            bases=(models.Model, a_predict.models.base_settings.ChoiceMethod),
        ),
        migrations.CreateModel(
            name='PsatUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='주석')),
                ('order', models.IntegerField()),
                ('exam', models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.prime_psat_exam_choices, default='행시', max_length=2, verbose_name='시험')),
                ('name', models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.prime_psat_unit_choices, default='5급공채', max_length=10, verbose_name='모집단위')),
            ],
            options={
                'verbose_name': 'PSAT 성적예측 [2] 모집단위',
                'verbose_name_plural': 'PSAT 성적예측 [2] 모집단위',
                'db_table': 'a_predict_psat_unit',
            },
        ),
        migrations.CreateModel(
            name='PsatStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='주석')),
                ('round', models.IntegerField(default=0, verbose_name='회차')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('serial', models.CharField(max_length=10, verbose_name='수험번호')),
                ('password', models.CharField(blank=True, max_length=10, null=True, verbose_name='비밀번호')),
                ('prime_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='프라임 ID')),
                ('answer', models.JSONField(default=dict, verbose_name='답안')),
                ('answer_count', models.JSONField(default=dict, verbose_name='답안 개수')),
                ('answer_confirmed', models.JSONField(default=dict, verbose_name='답안 확정')),
                ('answer_all_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='답안 전체 확정 일시')),
                ('score', models.JSONField(default=dict, verbose_name='점수')),
                ('rank_total', models.JSONField(default=dict, verbose_name='전체 등수')),
                ('rank_department', models.JSONField(default=dict, verbose_name='직렬 등수')),
                ('participants_total', models.JSONField(default=dict, verbose_name='전체 참여자수')),
                ('participants_department', models.JSONField(default=dict, verbose_name='직렬 참여자수')),
                ('year', models.IntegerField(choices=a_predict.models.base_settings.ChoiceMethod.year_choices, default=2024, verbose_name='연도')),
                ('exam', models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.prime_psat_exam_choices, default='행시', max_length=2, verbose_name='시험')),
                ('unit', models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.prime_psat_unit_choices, default='5급공채', max_length=20, verbose_name='모집단위')),
                ('department', models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.prime_psat_department_choices, default='일반행정', max_length=40, verbose_name='직렬')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PSAT 성적예측 [4] 수험정보',
                'verbose_name_plural': 'PSAT 성적예측 [4] 수험정보',
                'db_table': 'a_predict_psat_student',
            },
            bases=(models.Model, a_predict.models.base_settings.ChoiceMethod),
        ),
        migrations.CreateModel(
            name='PsatSubmittedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='주석')),
                ('number', models.IntegerField(choices=a_predict.models.base_settings.ChoiceMethod.number_choices, default=1, verbose_name='번호')),
                ('answer', models.IntegerField(choices=a_predict.models.base_settings.ChoiceMethod.answer_choices, default=0, verbose_name='제출답안')),
                ('subject', models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.psat_subject_choices, default='heonbeob', max_length=20, verbose_name='과목')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_answers', to='a_predict.psatstudent')),
            ],
            options={
                'verbose_name': 'PSAT 성적예측 [5] 제출답안',
                'verbose_name_plural': 'PSAT 성적예측 [5] 제출답안',
                'db_table': 'a_predict_psat_submitted_answer',
            },
        ),
    ]
