# Generated by Django 5.0.3 on 2024-07-11 07:58

import a_predict.models.base_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psatanswercount',
            name='exam',
            field=models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.psat_exam_choices, default='행시', max_length=2, verbose_name='시험'),
        ),
        migrations.AlterField(
            model_name='psatdepartment',
            name='exam',
            field=models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.psat_exam_choices, default='행시', max_length=2, verbose_name='시험'),
        ),
        migrations.AlterField(
            model_name='psatdepartment',
            name='name',
            field=models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.psat_department_choices, default='일반행정', max_length=40, verbose_name='직렬'),
        ),
        migrations.AlterField(
            model_name='psatdepartment',
            name='unit',
            field=models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.psat_unit_choices, default='5급공채', max_length=20, verbose_name='모집단위'),
        ),
        migrations.AlterField(
            model_name='psatexam',
            name='exam',
            field=models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.psat_exam_choices, default='행시', max_length=2, verbose_name='시험'),
        ),
        migrations.AlterField(
            model_name='psatstudent',
            name='department',
            field=models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.psat_department_choices, default='일반행정', max_length=40, verbose_name='직렬'),
        ),
        migrations.AlterField(
            model_name='psatstudent',
            name='exam',
            field=models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.psat_exam_choices, default='행시', max_length=2, verbose_name='시험'),
        ),
        migrations.AlterField(
            model_name='psatstudent',
            name='unit',
            field=models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.psat_unit_choices, default='5급공채', max_length=20, verbose_name='모집단위'),
        ),
        migrations.AlterField(
            model_name='psatunit',
            name='exam',
            field=models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.psat_exam_choices, default='행시', max_length=2, verbose_name='시험'),
        ),
        migrations.AlterField(
            model_name='psatunit',
            name='name',
            field=models.CharField(choices=a_predict.models.base_settings.ChoiceMethod.psat_unit_choices, default='5급공채', max_length=20, verbose_name='모집단위'),
        ),
    ]
