# Generated by Django 5.0.3 on 2024-07-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psatanswercount',
            name='all',
            field=models.JSONField(default=dict, verbose_name='전체'),
        ),
        migrations.AddField(
            model_name='psatanswercount',
            name='filtered',
            field=models.JSONField(default=dict, verbose_name='필터링'),
        ),
        migrations.AddField(
            model_name='psatexam',
            name='statistics',
            field=models.JSONField(default=dict, verbose_name='성적 통계'),
        ),
        migrations.AlterField(
            model_name='psatanswercount',
            name='count_multiple',
            field=models.IntegerField(default=0, verbose_name='중복표기'),
        ),
        migrations.AlterField(
            model_name='psatanswercount',
            name='count_total',
            field=models.IntegerField(default=0, verbose_name='총계'),
        ),
    ]
