# Generated by Django 5.0.3 on 2024-07-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0002_psatanswercount_all_psatanswercount_filtered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psatexam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
