# Generated by Django 5.0.3 on 2024-07-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0002_alter_psatanswercount_exam_alter_psatdepartment_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psatexam',
            name='participants_total',
            field=models.JSONField(default=dict, verbose_name='전체 참여자수'),
        ),
    ]
