# Generated by Django 5.0.3 on 2024-07-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0004_policeanswercount_policedepartment_policeexam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestudent',
            name='data',
            field=models.JSONField(default=list, verbose_name='답안 자료'),
        ),
        migrations.AddField(
            model_name='psatstudent',
            name='data',
            field=models.JSONField(default=list, verbose_name='답안 자료'),
        ),
    ]
