# Generated by Django 5.1 on 2025-01-27 07:48

import a_predict.models.base_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_predict', '0005_policestudent_data_psatstudent_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeanswercount',
            name='year',
            field=models.IntegerField(choices=a_predict.models.base_settings.ChoiceMethod.year_choices, default=2026, verbose_name='연도'),
        ),
        migrations.AlterField(
            model_name='policeexam',
            name='year',
            field=models.IntegerField(choices=a_predict.models.base_settings.ChoiceMethod.year_choices, default=2026, verbose_name='연도'),
        ),
        migrations.AlterField(
            model_name='policestudent',
            name='year',
            field=models.IntegerField(choices=a_predict.models.base_settings.ChoiceMethod.year_choices, default=2026, verbose_name='연도'),
        ),
        migrations.AlterField(
            model_name='psatanswercount',
            name='year',
            field=models.IntegerField(choices=a_predict.models.base_settings.ChoiceMethod.year_choices, default=2025, verbose_name='연도'),
        ),
        migrations.AlterField(
            model_name='psatexam',
            name='year',
            field=models.IntegerField(choices=a_predict.models.base_settings.ChoiceMethod.year_choices, default=2025, verbose_name='연도'),
        ),
        migrations.AlterField(
            model_name='psatstudent',
            name='year',
            field=models.IntegerField(choices=a_predict.models.base_settings.ChoiceMethod.year_choices, default=2025, verbose_name='연도'),
        ),
    ]
