# Generated by Django 4.2.5 on 2023-09-18 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('psat', '0007_alter_exam_ex_alter_exam_sub_alter_exam_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveSmallIntegerField(choices=[(1, '미니테스트 1회'), (2, '미니테스트 2회'), (3, '미니테스트 3회'), (4, '미니테스트 4회'), (5, '미니테스트 5회'), (6, '미니테스트 6회'), (7, '미니테스트 7회'), (8, '미니테스트 8회'), (9, '미니테스트 9회'), (10, '미니테스트 10회'), (11, '미니테스트 11회'), (12, '미니테스트 12회'), (13, '미니테스트 13회'), (14, '미니테스트 14회'), (15, '미니테스트 15회'), (16, '미니테스트 16회'), (17, '실전모의고사 1회'), (18, '실전모의고사 2회')])),
                ('question_num', models.PositiveSmallIntegerField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='psat.problem')),
            ],
            options={
                'ordering': ['chapter', 'question_num'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlphaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveSmallIntegerField(choices=[(1, '미니테스트 1회'), (2, '미니테스트 2회'), (3, '미니테스트 3회'), (4, '미니테스트 4회'), (5, '미니테스트 5회'), (6, '미니테스트 6회'), (7, '미니테스트 7회'), (8, '미니테스트 8회'), (9, '미니테스트 9회'), (10, '미니테스트 10회'), (11, '미니테스트 11회'), (12, '미니테스트 12회'), (13, '미니테스트 13회'), (14, '미니테스트 14회'), (15, '미니테스트 15회'), (16, '미니테스트 16회'), (17, '실전모의고사 1회'), (18, '실전모의고사 2회')])),
                ('question_num', models.PositiveSmallIntegerField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='psat.problem')),
            ],
            options={
                'ordering': ['chapter', 'question_num'],
                'abstract': False,
            },
        ),
    ]
