# Generated by Django 4.2.5 on 2023-09-21 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psat', '0007_alter_exam_ex_alter_exam_sub_alter_exam_year'),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, '기본 과정'), (2, '심화 과정')])),
                ('chapter', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['category', 'chapter'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='study.chapter')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_questions', to='psat.problem')),
            ],
            options={
                'ordering': ['chapter', 'number'],
            },
        ),
        migrations.RemoveField(
            model_name='betaquestion',
            name='problem',
        ),
        migrations.DeleteModel(
            name='AlphaQuestion',
        ),
        migrations.DeleteModel(
            name='BetaQuestion',
        ),
    ]
