# Generated by Django 4.2.5 on 2023-09-21 03:51

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import study.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0002_chapter_question_remove_betaquestion_problem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField(choices=[(1, '일반'), (2, '사용팁'), (3, '공부법')], default=1, verbose_name='카테고리')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('hit', models.IntegerField(default=1, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('top_fixed', models.BooleanField(default=False, verbose_name='상단 고정')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='비밀글')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='study_user', to=settings.AUTH_USER_MODEL, verbose_name='사용자 ID')),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=(study.models.PostInfo, models.Model),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='study_post_comments', to='study.post', verbose_name='게시글')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='study_user_comments', to=settings.AUTH_USER_MODEL, verbose_name='사용자 ID')),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=(study.models.CommentInfo, models.Model),
        ),
    ]
