# Generated by Django 5.0.1 on 2024-02-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(choices=[('PSAT', 'PSAT'), ('Prime', '프라임')], max_length=20),
        ),
    ]
