# Generated by Django 5.0.1 on 2024-02-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_alter_exam_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='answer_file',
        ),
    ]
