# Generated by Django 5.0.1 on 2024-02-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_remove_exam_answer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='unit_id',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
