# Generated by Django 5.0.1 on 2024-02-24 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_student_unit_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_start', models.IntegerField()),
                ('serial_end', models.IntegerField()),
                ('region', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='predict.exam')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
