# Generated by Django 5.0.1 on 2024-02-26 03:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='predict_open_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
