# Generated by Django 5.0.2 on 2024-02-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0006_exam_predict_open_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prime_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
