# Generated by Django 5.0.2 on 2024-03-01 03:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0008_rename_answer_open_date_exam_answer_open_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='answer_predict_open_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exam',
            name='answer_open_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(choices=[('PSAT', 'PSAT'), ('Prime', '프라임')], default='PSAT', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exam',
            name='ex',
            field=models.CharField(choices=[('행시', '5급공채'), ('입시', '입법고시'), ('칠급', '7급공채'), ('민경', '민간경력'), ('프모', '프라임 모의고사')], default='행시', max_length=2),
        ),
        migrations.AlterField(
            model_name='exam',
            name='round',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
