# Generated by Django 5.0.3 on 2024-03-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0011_answercountlowrank_answercountmiddlerank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerCountMiddleRank',
            new_name='AnswerCountMidRank',
        ),
    ]
