# Generated by Django 3.2.19 on 2023-07-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlog',
            name='session_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problemlog',
            name='session_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='session_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
