# Generated by Django 3.2.19 on 2023-07-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20230705_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='log_url',
            field=models.TextField(),
        ),
    ]
