# Generated by Django 3.2.19 on 2023-07-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_alter_requestlog_log_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlog',
            name='log_url',
            field=models.TextField(),
        ),
    ]
