# Generated by Django 4.2.5 on 2023-10-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psat',
            options={'ordering': ['-year', 'id']},
        ),
        migrations.AlterModelOptions(
            name='psatproblem',
            options={'ordering': ['-psat__year', 'id']},
        ),
    ]
