# Generated by Django 4.2.5 on 2023-11-09 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_alter_psat_options_alter_psatproblem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psat',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_exams', to='reference.exam'),
        ),
        migrations.AlterField(
            model_name='psat',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_exams', to='reference.subject'),
        ),
    ]
