# Generated by Django 4.2.5 on 2023-11-09 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_alter_psat_exam_alter_psat_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('round', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_exams', to='reference.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_exams', to='reference.subject')),
            ],
            options={
                'ordering': ['-year', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrimeProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prime_problems', to='reference.prime')),
                ('number', models.IntegerField()),
                ('answer', models.IntegerField()),
            ],
            options={
                'ordering': ['-prime__year', 'id'],
            },
        ),
    ]
