# Generated by Django 4.2.5 on 2024-01-11 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_prime_primeproblem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='reference.exam')),
            ],
            options={
                'verbose_name': '모집단위',
                'verbose_name_plural': '모집단위',
            },
        ),
        migrations.CreateModel(
            name='UnitDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='reference.unit')),
            ],
            options={
                'verbose_name': '직렬',
                'verbose_name_plural': '직렬',
            },
        ),
    ]
