# Generated by Django 4.2.4 on 2023-09-07 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('psat', '0004_alter_problemtag_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(verbose_name='제출 답안')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='확정 여부')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psat.problem', verbose_name='문제 ID')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='사용자 ID')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(verbose_name='제출 답안')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_times', models.IntegerField(default=1, verbose_name='확정 횟수')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psat.problem', verbose_name='문제 ID')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='사용자 ID')),
            ],
        ),
    ]
