# Generated by Django 4.2.4 on 2023-09-10 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psat', '0006_alter_problem_exam'),
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedanswer',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_answers', to='psat.problem', verbose_name='문제 ID'),
        ),
        migrations.AlterField(
            model_name='temporaryanswer',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_answers', to='psat.problem', verbose_name='문제 ID'),
        ),
    ]
