# Generated by Django 4.2.5 on 2023-12-23 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('score', '0002_remove_primestudent_eoneo_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primestudent',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='primestudent',
            name='serial',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PrimeVerifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prime_verified_users', to='score.primestudent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prime_verified_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
