# Generated by Django 4.2.5 on 2023-09-23 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_alter_temporaryanswer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryanswer',
            name='is_confirmed',
        ),
    ]
