# Generated by Django 4.2.5 on 2023-09-25 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psat', '0008_alter_problem_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('score', '0004_remove_temporaryanswer_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자 ID'),
        ),
        migrations.CreateModel(
            name='DummyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('answer', models.IntegerField(verbose_name='제출 답안')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_times', models.IntegerField(default=1, verbose_name='확정 횟수')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dummy_answers', to='psat.problem', verbose_name='문제 ID')),
            ],
        ),
    ]
