# Generated by Django 4.2.5 on 2024-01-01 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_psatanswertemporary_psatanswerconfirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsatStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('score_eoneo', models.FloatField(blank=True, null=True)),
                ('score_jaryo', models.FloatField(blank=True, null=True)),
                ('score_sanghwang', models.FloatField(blank=True, null=True)),
                ('score_psat', models.FloatField(blank=True, null=True)),
                ('score_psat_avg', models.FloatField(blank=True, null=True)),
                ('score_heonbeob', models.FloatField(blank=True, null=True)),
                ('rank_total_eoneo', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_total_jaryo', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_total_sanghwang', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_total_psat', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_total_heonbeob', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_department_eoneo', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_department_jaryo', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_department_sanghwang', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_department_psat', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_department_heonbeob', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_ratio_total_eoneo', models.FloatField(blank=True, null=True)),
                ('rank_ratio_total_jaryo', models.FloatField(blank=True, null=True)),
                ('rank_ratio_total_sanghwang', models.FloatField(blank=True, null=True)),
                ('rank_ratio_total_psat', models.FloatField(blank=True, null=True)),
                ('rank_ratio_total_heonbeob', models.FloatField(blank=True, null=True)),
                ('rank_ratio_department_eoneo', models.FloatField(blank=True, null=True)),
                ('rank_ratio_department_jaryo', models.FloatField(blank=True, null=True)),
                ('rank_ratio_department_sanghwang', models.FloatField(blank=True, null=True)),
                ('rank_ratio_department_psat', models.FloatField(blank=True, null=True)),
                ('rank_ratio_department_heonbeob', models.FloatField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='score.psatstudent')),
            ],
        ),
    ]
