# Generated by Django 4.2.5 on 2023-09-25 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psat', '0008_alter_problem_answer'),
        ('score', '0005_alter_confirmedanswer_user_dummyanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_1', models.IntegerField()),
                ('count_2', models.IntegerField()),
                ('count_3', models.IntegerField()),
                ('count_4', models.IntegerField()),
                ('count_5', models.IntegerField()),
                ('count_total', models.IntegerField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_counts', to='psat.problem', verbose_name='문제 ID')),
            ],
        ),
    ]
