# Generated by Django 4.2.5 on 2024-01-04 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_psatstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='primeverifieduser',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
