# Generated by Django 4.2.5 on 2023-09-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_answercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercount',
            name='count_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answercount',
            name='count_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answercount',
            name='count_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answercount',
            name='count_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answercount',
            name='count_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answercount',
            name='count_total',
            field=models.IntegerField(default=0),
        ),
    ]
