# Generated by Django 4.2.5 on 2023-09-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0007_alter_answercount_count_1_alter_answercount_count_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answercount',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='confirmedanswer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='dummyanswer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='temporaryanswer',
            options={'ordering': ['id']},
        ),
    ]
