# Generated by Django 4.2.5 on 2023-10-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0009_department_unit_alter_answercount_problem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answercount',
            options={'ordering': ['id'], 'verbose_name': '답안 개수(통계용)'},
        ),
        migrations.AlterModelOptions(
            name='confirmedanswer',
            options={'ordering': ['id'], 'verbose_name': '답안(최종 제출용)'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id'], 'verbose_name': '직렬'},
        ),
        migrations.AlterModelOptions(
            name='dummyanswer',
            options={'ordering': ['id'], 'verbose_name': '답안(테스트용)'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id'], 'verbose_name': '수험 정보'},
        ),
        migrations.AlterModelOptions(
            name='temporaryanswer',
            options={'ordering': ['id'], 'verbose_name': '답안(임시 저장용)'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['id'], 'verbose_name': '모집단위'},
        ),
    ]
