# Generated by Django 5.0.1 on 2024-01-19 23:30

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0009_alter_predictanswercount_count_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='primeanswercount',
            name='rate_1',
            field=models.GeneratedField(db_persist=False, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('count_1'), '*', models.Value(100)), '/', models.F('count_total')), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='primeanswercount',
            name='rate_2',
            field=models.GeneratedField(db_persist=False, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('count_2'), '*', models.Value(100)), '/', models.F('count_total')), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='primeanswercount',
            name='rate_3',
            field=models.GeneratedField(db_persist=False, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('count_3'), '*', models.Value(100)), '/', models.F('count_total')), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='primeanswercount',
            name='rate_4',
            field=models.GeneratedField(db_persist=False, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('count_4'), '*', models.Value(100)), '/', models.F('count_total')), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='primeanswercount',
            name='rate_5',
            field=models.GeneratedField(db_persist=False, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('count_5'), '*', models.Value(100)), '/', models.F('count_total')), output_field=models.FloatField()),
        ),
        migrations.AlterField(
            model_name='primeanswercount',
            name='count_total',
            field=models.IntegerField(default=1),
        ),
    ]
