# Generated by Django 5.0.1 on 2024-01-20 12:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0010_primeanswercount_rate_1_primeanswercount_rate_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictanswercount',
            options={'verbose_name': '성적 예측 답안 개수', 'verbose_name_plural': '성적 예측 답안 개수'},
        ),
        migrations.AlterModelOptions(
            name='predictstatistics',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='predictanswercount',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictanswercount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='predictstatistics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PredictStatisticsVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_heonbeob', models.FloatField(blank=True, null=True)),
                ('score_eoneo', models.FloatField(blank=True, null=True)),
                ('score_jaryo', models.FloatField(blank=True, null=True)),
                ('score_sanghwang', models.FloatField(blank=True, null=True)),
                ('score_psat', models.FloatField(blank=True, null=True)),
                ('score_psat_avg', models.FloatField(blank=True, null=True)),
                ('rank_total_heonbeob', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_total_eoneo', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_total_jaryo', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_total_sanghwang', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_total_psat', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_department_heonbeob', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_department_eoneo', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_department_jaryo', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_department_sanghwang', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_department_psat', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_ratio_total_heonbeob', models.FloatField(blank=True, null=True)),
                ('rank_ratio_total_eoneo', models.FloatField(blank=True, null=True)),
                ('rank_ratio_total_jaryo', models.FloatField(blank=True, null=True)),
                ('rank_ratio_total_sanghwang', models.FloatField(blank=True, null=True)),
                ('rank_ratio_total_psat', models.FloatField(blank=True, null=True)),
                ('rank_ratio_department_heonbeob', models.FloatField(blank=True, null=True)),
                ('rank_ratio_department_eoneo', models.FloatField(blank=True, null=True)),
                ('rank_ratio_department_jaryo', models.FloatField(blank=True, null=True)),
                ('rank_ratio_department_sanghwang', models.FloatField(blank=True, null=True)),
                ('rank_ratio_department_psat', models.FloatField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics_virtual', to='score.predictstudent')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
