# Generated by Django 4.2.5 on 2023-10-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0011_alter_answercount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['id'], 'verbose_name': '모집단위', 'verbose_name_plural': '모집단위'},
        ),
    ]
