# Generated by Django 4.2.5 on 2023-10-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0013_remove_student_exam_student_ex_student_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ex',
        ),
        migrations.AddField(
            model_name='student',
            name='serial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='ex',
            field=models.CharField(choices=[('행시', '5급공채/행정고시'), ('외시', '외교원/외무고시'), ('칠급', '7급공채'), ('민경', '민간경력'), ('견습', '견습'), ('입시', '입법고시')], default='행시', max_length=2),
            preserve_default=False,
        ),
    ]
