# Generated by Django 4.2.5 on 2023-10-14 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0015_dummystudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummyanswer',
            name='user',
        ),
        migrations.AddField(
            model_name='dummyanswer',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dummy_answers', to='score.dummystudent'),
            preserve_default=False,
        ),
    ]
