# Generated by Django 4.2.5 on 2023-10-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0016_remove_dummyanswer_user_dummyanswer_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummystudent',
            name='eoneo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dummystudent',
            name='jaryo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dummystudent',
            name='sanghwang',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
