# Generated by Django 4.2.5 on 2023-10-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0017_dummystudent_eoneo_dummystudent_jaryo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummystudent',
            name='psat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
