# Generated by Django 4.2.5 on 2023-10-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0018_dummystudent_psat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dummystudent',
            old_name='eoneo',
            new_name='eoneo_score',
        ),
        migrations.RenameField(
            model_name='dummystudent',
            old_name='jaryo',
            new_name='jaryo_score',
        ),
        migrations.RenameField(
            model_name='dummystudent',
            old_name='psat',
            new_name='psat_score',
        ),
        migrations.RenameField(
            model_name='dummystudent',
            old_name='sanghwang',
            new_name='sanghwang_score',
        ),
    ]
