# Generated by Django 4.2.5 on 2023-10-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0019_rename_eoneo_dummystudent_eoneo_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='eoneo_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='jaryo_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='psat_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sanghwang_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
