# Generated by Django 4.2.5 on 2023-11-03 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_alter_psat_options_alter_psatproblem_options'),
        ('score', '0020_student_eoneo_score_student_jaryo_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsatUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='reference.exam')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '모집단위',
                'verbose_name_plural': '모집단위',
            },
        ),
        migrations.CreateModel(
            name='PsatUnitDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='score.psatunit')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '직렬',
                'verbose_name_plural': '직렬',
            },
        ),
        migrations.CreateModel(
            name='PsatTemporaryAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_answers', to='reference.psatproblem')),
                ('answer', models.IntegerField(verbose_name='제출 답안')),
            ],
            options={
                'verbose_name': '답안(임시 저장용)',
                'verbose_name_plural': '답안(임시 저장용)',
            },
        ),
        migrations.CreateModel(
            name='PsatStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='score.psatunitdepartment')),
                ('serial', models.CharField(blank=True, max_length=20, null=True)),
                ('heonbeob_score', models.FloatField(blank=True, null=True)),
                ('eoneo_score', models.FloatField(blank=True, null=True)),
                ('jaryo_score', models.FloatField(blank=True, null=True)),
                ('sanghwang_score', models.FloatField(blank=True, null=True)),
                ('psat_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '수험 정보',
                'verbose_name_plural': '수험 정보',
            },
        ),
        migrations.CreateModel(
            name='PsatConfirmedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_answers', to='reference.psatproblem')),
                ('answer', models.IntegerField(verbose_name='제출 답안')),
                ('confirmed_times', models.IntegerField(default=1, verbose_name='확정 횟수')),
            ],
            options={
                'verbose_name': '답안(최종 제출용)',
                'verbose_name_plural': '답안(최종 제출용)',
            },
        ),
        migrations.CreateModel(
            name='PsatAnswerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_counts', to='reference.psatproblem')),
                ('count_1', models.IntegerField(default=0)),
                ('count_2', models.IntegerField(default=0)),
                ('count_3', models.IntegerField(default=0)),
                ('count_4', models.IntegerField(default=0)),
                ('count_5', models.IntegerField(default=0)),
                ('count_total', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '답안 개수(통계용)',
                'verbose_name_plural': '답안 개수(통계용)',
                'ordering': ['id'],
            },
        ),
    ]
