# Generated by Django 4.2.5 on 2023-11-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0021_psatunit_psatunitdepartment_psattemporaryanswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psatstudent',
            name='eoneo_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='psatstudent',
            name='heonbeob_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='psatstudent',
            name='jaryo_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='psatstudent',
            name='psat_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='psatstudent',
            name='sanghwang_score',
            field=models.FloatField(default=0),
        ),
    ]
