# Generated by Django 4.2.5 on 2023-11-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0022_alter_psatstudent_eoneo_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psatconfirmedanswer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='psatstudent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='psattemporaryanswer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
