# Generated by Django 4.2.5 on 2023-11-12 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_prime_primeproblem'),
        ('score', '0023_alter_psatconfirmedanswer_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prime_units', to='reference.exam')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '직렬',
                'verbose_name_plural': '직렬',
            },
        ),
        migrations.CreateModel(
            name='PrimeStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField()),
                ('round', models.IntegerField()),
                ('serial', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=10)),
                ('password', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='score.primedepartment')),
                ('eoneo_score', models.FloatField(default=0)),
                ('jaryo_score', models.FloatField(default=0)),
                ('sanghwang_score', models.FloatField(default=0)),
                ('psat_score', models.FloatField(default=0)),
                ('heonbeob_score', models.FloatField(default=0)),
                ('user_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '수험 정보',
                'verbose_name_plural': '수험 정보',
            },
        ),
        migrations.CreateModel(
            name='PrimeAnswerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_counts', to='reference.primeproblem')),
                ('count_0', models.IntegerField(default=0)),
                ('count_1', models.IntegerField(default=0)),
                ('count_2', models.IntegerField(default=0)),
                ('count_3', models.IntegerField(default=0)),
                ('count_4', models.IntegerField(default=0)),
                ('count_5', models.IntegerField(default=0)),
                ('count_total', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '답안 개수',
                'verbose_name_plural': '답안 개수',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PrimeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prime_answers', to='reference.prime')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='score.primestudent')),
                ('prob1', models.IntegerField(blank=True, null=True)),
                ('prob2', models.IntegerField(blank=True, null=True)),
                ('prob3', models.IntegerField(blank=True, null=True)),
                ('prob4', models.IntegerField(blank=True, null=True)),
                ('prob5', models.IntegerField(blank=True, null=True)),
                ('prob6', models.IntegerField(blank=True, null=True)),
                ('prob7', models.IntegerField(blank=True, null=True)),
                ('prob8', models.IntegerField(blank=True, null=True)),
                ('prob9', models.IntegerField(blank=True, null=True)),
                ('prob10', models.IntegerField(blank=True, null=True)),
                ('prob11', models.IntegerField(blank=True, null=True)),
                ('prob12', models.IntegerField(blank=True, null=True)),
                ('prob13', models.IntegerField(blank=True, null=True)),
                ('prob14', models.IntegerField(blank=True, null=True)),
                ('prob15', models.IntegerField(blank=True, null=True)),
                ('prob16', models.IntegerField(blank=True, null=True)),
                ('prob17', models.IntegerField(blank=True, null=True)),
                ('prob18', models.IntegerField(blank=True, null=True)),
                ('prob19', models.IntegerField(blank=True, null=True)),
                ('prob20', models.IntegerField(blank=True, null=True)),
                ('prob21', models.IntegerField(blank=True, null=True)),
                ('prob22', models.IntegerField(blank=True, null=True)),
                ('prob23', models.IntegerField(blank=True, null=True)),
                ('prob24', models.IntegerField(blank=True, null=True)),
                ('prob25', models.IntegerField(blank=True, null=True)),
                ('prob26', models.IntegerField(blank=True, null=True)),
                ('prob27', models.IntegerField(blank=True, null=True)),
                ('prob28', models.IntegerField(blank=True, null=True)),
                ('prob29', models.IntegerField(blank=True, null=True)),
                ('prob30', models.IntegerField(blank=True, null=True)),
                ('prob31', models.IntegerField(blank=True, null=True)),
                ('prob32', models.IntegerField(blank=True, null=True)),
                ('prob33', models.IntegerField(blank=True, null=True)),
                ('prob34', models.IntegerField(blank=True, null=True)),
                ('prob35', models.IntegerField(blank=True, null=True)),
                ('prob36', models.IntegerField(blank=True, null=True)),
                ('prob37', models.IntegerField(blank=True, null=True)),
                ('prob38', models.IntegerField(blank=True, null=True)),
                ('prob39', models.IntegerField(blank=True, null=True)),
                ('prob40', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '제출 답안',
                'verbose_name_plural': '제출 답안',
            },
        ),
    ]
