# Generated by Django 4.2.5 on 2023-10-29 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0002_alter_psat_options_alter_psatproblem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsatSolveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('session_key', models.TextField(blank=True, null=True)),
                ('data_id', models.IntegerField()),
                ('repetition', models.IntegerField()),
                ('answer', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='reference.psatproblem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PsatRateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('session_key', models.TextField(blank=True, null=True)),
                ('data_id', models.IntegerField()),
                ('repetition', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='reference.psatproblem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PsatOpenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('session_key', models.TextField(blank=True, null=True)),
                ('data_id', models.IntegerField()),
                ('repetition', models.IntegerField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='reference.psatproblem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PsatLikeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('session_key', models.TextField(blank=True, null=True)),
                ('data_id', models.IntegerField()),
                ('repetition', models.IntegerField()),
                ('is_liked', models.BooleanField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='reference.psatproblem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
