# Generated by Django 5.1 on 2025-02-12 05:01

import a_prime_leet.models.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_prime_leet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leet',
            name='round',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='회차'),
        ),
        migrations.AlterField(
            model_name='leet',
            name='year',
            field=models.PositiveSmallIntegerField(choices=a_prime_leet.models.choices.year_choice, default=2026, verbose_name='연도'),
        ),
    ]
