# Generated by Django 5.1 on 2025-01-27 07:48

import a_prime_leet.models.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_prime_leet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leet',
            name='year',
            field=models.IntegerField(choices=a_prime_leet.models.choices.year_choice, default=2025, verbose_name='연도'),
        ),
    ]
