# Generated by Django 5.1 on 2025-02-11 10:09

import a_prime_leet.models.abstract_models
import a_prime_leet.models.choices
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_prime_leet', '0002_alter_leet_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultRankAspiration1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_0', models.IntegerField(blank=True, null=True, verbose_name='언어이해 등수')),
                ('subject_1', models.IntegerField(blank=True, null=True, verbose_name='추리논증 등수')),
                ('sum', models.IntegerField(blank=True, null=True, verbose_name='총점 등수')),
                ('participants', models.IntegerField(blank=True, null=True, verbose_name='총 인원')),
            ],
            options={
                'verbose_name': '[성적확인] 07_등수(1지망)',
                'verbose_name_plural': '[성적확인] 07_등수(1지망)',
                'db_table': 'a_prime_leet_result_rank_aspiration_1',
            },
        ),
        migrations.CreateModel(
            name='ResultRankAspiration2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_0', models.IntegerField(blank=True, null=True, verbose_name='언어이해 등수')),
                ('subject_1', models.IntegerField(blank=True, null=True, verbose_name='추리논증 등수')),
                ('sum', models.IntegerField(blank=True, null=True, verbose_name='총점 등수')),
                ('participants', models.IntegerField(blank=True, null=True, verbose_name='총 인원')),
            ],
            options={
                'verbose_name': '[성적확인] 08_등수(2지망)',
                'verbose_name_plural': '[성적확인] 08_등수(2지망)',
                'db_table': 'a_prime_leet_result_rank_aspiration_2',
            },
        ),
        migrations.AlterModelOptions(
            name='leet',
            options={'ordering': ['-id'], 'verbose_name': '[프라임LEET] 00_LEET 모의고사', 'verbose_name_plural': '[프라임LEET] 00_LEET 모의고사'},
        ),
        migrations.AlterModelOptions(
            name='resultanswercountlowrank',
            options={'verbose_name': '[성적확인] 11_답안 개수(하위권)', 'verbose_name_plural': '[성적확인] 11_답안 개수(하위권)'},
        ),
        migrations.AlterModelOptions(
            name='resultanswercountmidrank',
            options={'verbose_name': '[성적확인] 10_답안 개수(중위권)', 'verbose_name_plural': '[성적확인] 10_답안 개수(중위권)'},
        ),
        migrations.AlterModelOptions(
            name='resultanswercounttoprank',
            options={'verbose_name': '[성적확인] 09_답안 개수(상위권)', 'verbose_name_plural': '[성적확인] 09_답안 개수(상위권)'},
        ),
        migrations.AlterModelOptions(
            name='resultrank',
            options={'verbose_name': '[성적확인] 06_등수(전체)', 'verbose_name_plural': '[성적확인] 06_등수(전체)'},
        ),
        migrations.RemoveConstraint(
            model_name='leet',
            name='unique_prime_leet_leet',
        ),
        migrations.AddField(
            model_name='leet',
            name='abbr',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='약칭'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leet',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='시험명'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultstatistics',
            name='aspiration',
            field=models.CharField(choices=a_prime_leet.models.choices.statistics_aspiration_choice, default='전체', max_length=10, verbose_name='지망 대학'),
        ),
        migrations.AddField(
            model_name='resultstudent',
            name='aspiration_1',
            field=models.CharField(blank=True, choices=a_prime_leet.models.choices.university_choice, max_length=10, null=True, verbose_name='1지망'),
        ),
        migrations.AddField(
            model_name='resultstudent',
            name='aspiration_2',
            field=models.CharField(blank=True, choices=a_prime_leet.models.choices.university_choice, max_length=10, null=True, verbose_name='2지망'),
        ),
        migrations.AddField(
            model_name='resultstudent',
            name='english',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='공인 영어성적'),
        ),
        migrations.AddField(
            model_name='resultstudent',
            name='english_type',
            field=models.CharField(blank=True, choices=a_prime_leet.models.choices.english_type_choice, max_length=10, null=True, verbose_name='공인 영어성적 종류'),
        ),
        migrations.AddField(
            model_name='resultstudent',
            name='gpa',
            field=models.FloatField(blank=True, null=True, verbose_name='학점(GPA)'),
        ),
        migrations.AddField(
            model_name='resultstudent',
            name='gpa_type',
            field=models.FloatField(blank=True, choices=a_prime_leet.models.choices.gpa_type_choice, null=True, verbose_name='학점(GPA) 종류'),
        ),
        migrations.AddField(
            model_name='resultstudent',
            name='major',
            field=models.CharField(blank=True, choices=a_prime_leet.models.choices.major_choice, max_length=5, null=True, verbose_name='전공'),
        ),
        migrations.AddField(
            model_name='resultstudent',
            name='school',
            field=models.CharField(blank=True, choices=a_prime_leet.models.choices.university_choice, max_length=10, null=True, verbose_name='출신대학'),
        ),
        migrations.AlterField(
            model_name='leet',
            name='year',
            field=models.IntegerField(choices=a_prime_leet.models.choices.year_choice, default=2026, verbose_name='연도'),
        ),
        migrations.AlterField(
            model_name='resultstatistics',
            name='leet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_statistics', to='a_prime_leet.leet'),
        ),
        migrations.AlterField(
            model_name='resultstatistics',
            name='raw_subject_0',
            field=models.JSONField(default=a_prime_leet.models.abstract_models.get_default_statistics, verbose_name='언어이해 원점수'),
        ),
        migrations.AlterField(
            model_name='resultstatistics',
            name='raw_subject_1',
            field=models.JSONField(default=a_prime_leet.models.abstract_models.get_default_statistics, verbose_name='추리논증 원점수'),
        ),
        migrations.AlterField(
            model_name='resultstatistics',
            name='raw_sum',
            field=models.JSONField(default=a_prime_leet.models.abstract_models.get_default_statistics, verbose_name='총점 원점수'),
        ),
        migrations.AlterField(
            model_name='resultstatistics',
            name='subject_0',
            field=models.JSONField(default=a_prime_leet.models.abstract_models.get_default_statistics, verbose_name='언어이해 표준점수'),
        ),
        migrations.AlterField(
            model_name='resultstatistics',
            name='subject_1',
            field=models.JSONField(default=a_prime_leet.models.abstract_models.get_default_statistics, verbose_name='추리논증 표준점수'),
        ),
        migrations.AlterField(
            model_name='resultstatistics',
            name='sum',
            field=models.JSONField(default=a_prime_leet.models.abstract_models.get_default_statistics, verbose_name='총점 표준점수'),
        ),
        migrations.AddConstraint(
            model_name='leet',
            constraint=models.UniqueConstraint(fields=('year', 'exam', 'name'), name='unique_prime_leet_leet'),
        ),
        migrations.AddField(
            model_name='resultrankaspiration1',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rank_aspiration_1', to='a_prime_leet.resultstudent'),
        ),
        migrations.AddField(
            model_name='resultrankaspiration2',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rank_aspiration_2', to='a_prime_leet.resultstudent'),
        ),
    ]
