# Generated by Django 5.1 on 2025-03-20 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_prime_leet', '0003_predictanswer_predictanswercount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leet',
            name='predict_closed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='성적 에측 종료 일시'),
        ),
    ]
