# Generated by Django 5.2.4 on 2025-07-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_prime_leet', '0005_fakeanswercount_fakeanswercountlowrank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='시험명'),
        ),
    ]
