# Generated by Django 3.2.19 on 2023-06-19 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='상세 내용')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='상세 내용')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='시작일')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='시작 시각')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='종료 시각')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='종료일')),
                ('all_day', models.BooleanField(default=True, verbose_name='종일')),
                ('calendar', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.calendar', verbose_name='캘린더')),
                ('user', models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자 ID')),
            ],
        ),
    ]
