# Generated by Django 3.2.19 on 2023-06-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hit',
            field=models.IntegerField(default=1, verbose_name='조회수'),
        ),
    ]
