# Generated by Django 3.2.19 on 2023-06-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_alter_post_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='top_fixed',
            field=models.BooleanField(default=False, verbose_name='상단 고정'),
        ),
    ]
