# Generated by Django 3.2.19 on 2023-06-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_alter_post_top_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(1, '일반'), (2, '사용팁')], default=1, verbose_name='카테고리'),
        ),
    ]
