# Generated by Django 3.2.19 on 2023-07-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
    ]
