# Generated by Django 3.2.19 on 2023-09-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0010_auto_20230823_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='비밀글'),
        ),
    ]
