# Generated by Django 5.1 on 2024-11-21 05:56

import a_prime.models.choices
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(choices=a_prime.models.choices.exam_choice, default='프모', max_length=2, verbose_name='시험')),
                ('unit', models.CharField(choices=a_prime.models.choices.unit_choice, default='5급 행정', max_length=20, verbose_name='모집단위')),
                ('department', models.CharField(choices=a_prime.models.choices.department_choices, default='5급 일반행정', max_length=40, verbose_name='직렬')),
                ('order', models.SmallIntegerField(default=1, verbose_name='순서')),
            ],
            options={
                'verbose_name': '[프라임] 03_모집단위 및 직렬',
                'verbose_name_plural': '[프라임] 03_모집단위 및 직렬',
                'constraints': [models.UniqueConstraint(fields=('exam', 'unit', 'department'), name='unique_prime_category')],
            },
        ),
        migrations.CreateModel(
            name='Psat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=a_prime.models.choices.year_choice, default=2024, verbose_name='연도')),
                ('exam', models.CharField(choices=a_prime.models.choices.exam_choice, default='프모', max_length=2, verbose_name='시험')),
                ('round', models.IntegerField(choices=a_prime.models.choices.round_choice, verbose_name='회차')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성')),
                ('page_opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='페이지 오픈 일시')),
                ('exam_started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='시험 시작 일시')),
                ('exam_finished_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='시험 종료 일시')),
                ('answer_predict_opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='예상 정답 공개 일시')),
                ('answer_official_opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='공식 정답 공개 일시')),
            ],
            options={
                'verbose_name': '[프라임] 00_PSAT 모의고사',
                'verbose_name_plural': '[프라임] 00_PSAT 모의고사',
                'ordering': ['-year', 'round'],
                'constraints': [models.UniqueConstraint(fields=('year', 'exam', 'round'), name='unique_prime_psat')],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=a_prime.models.choices.subject_choice, default='언어', max_length=2, verbose_name='과목')),
                ('number', models.IntegerField(choices=a_prime.models.choices.number_choice, default=1, verbose_name='번호')),
                ('answer', models.IntegerField(choices=a_prime.models.choices.answer_choice, default=1, verbose_name='정답')),
                ('psat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='a_prime.psat', verbose_name='PSAT')),
            ],
            options={
                'verbose_name': '[프라임] 01_문제',
                'verbose_name_plural': '[프라임] 01_문제',
                'ordering': ['psat', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResultAnswerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_1', models.IntegerField(default=0, verbose_name='①')),
                ('count_2', models.IntegerField(default=0, verbose_name='②')),
                ('count_3', models.IntegerField(default=0, verbose_name='③')),
                ('count_4', models.IntegerField(default=0, verbose_name='④')),
                ('count_5', models.IntegerField(default=0, verbose_name='⑤')),
                ('count_0', models.IntegerField(default=0, verbose_name='미표기')),
                ('count_multiple', models.IntegerField(default=0, verbose_name='중복표기')),
                ('count_total', models.IntegerField(default=0, verbose_name='총계')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_answer_count', to='a_prime.problem')),
            ],
            options={
                'verbose_name': '[성적확인] 04_답안 개수',
                'verbose_name_plural': '[성적확인] 04_답안 개수',
                'db_table': 'a_prime_result_answer_count',
            },
        ),
        migrations.CreateModel(
            name='ResultStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('serial', models.CharField(max_length=10, verbose_name='수험번호')),
                ('password', models.CharField(blank=True, max_length=10, null=True, verbose_name='비밀번호')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_students', to='a_prime.category')),
                ('psat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_students', to='a_prime.psat')),
            ],
            options={
                'verbose_name': '[성적확인] 01_수험정보',
                'verbose_name_plural': '[성적확인] 01_수험정보',
                'db_table': 'a_prime_result_student',
            },
        ),
        migrations.CreateModel(
            name='ResultScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_0', models.FloatField(blank=True, null=True, verbose_name='헌법')),
                ('subject_1', models.FloatField(blank=True, null=True, verbose_name='언어논리')),
                ('subject_2', models.FloatField(blank=True, null=True, verbose_name='자료해석')),
                ('subject_3', models.FloatField(blank=True, null=True, verbose_name='상황판단')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='PSAT 총점')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='a_prime.resultstudent')),
            ],
            options={
                'verbose_name': '[성적확인] 05_점수',
                'verbose_name_plural': '[성적확인] 05_점수',
                'db_table': 'a_prime_result_score',
            },
        ),
        migrations.CreateModel(
            name='ResultRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prime_result_registries', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registries', to='a_prime.resultstudent')),
            ],
            options={
                'verbose_name': '[성적확인] 02_수험정보 연결',
                'verbose_name_plural': '[성적확인] 02_수험정보 연결',
                'db_table': 'a_prime_result_registry',
            },
        ),
        migrations.CreateModel(
            name='ResultRankTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_0', models.FloatField(blank=True, null=True, verbose_name='헌법')),
                ('subject_1', models.FloatField(blank=True, null=True, verbose_name='언어논리')),
                ('subject_2', models.FloatField(blank=True, null=True, verbose_name='자료해석')),
                ('subject_3', models.FloatField(blank=True, null=True, verbose_name='상황판단')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='PSAT')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rank_total', to='a_prime.resultstudent')),
            ],
            options={
                'verbose_name': '[성적확인] 06_전체 등수',
                'verbose_name_plural': '[성적확인] 06_전체 등수',
                'db_table': 'a_prime_result_rank_total',
            },
        ),
        migrations.CreateModel(
            name='ResultRankCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_0', models.FloatField(blank=True, null=True, verbose_name='헌법')),
                ('subject_1', models.FloatField(blank=True, null=True, verbose_name='언어논리')),
                ('subject_2', models.FloatField(blank=True, null=True, verbose_name='자료해석')),
                ('subject_3', models.FloatField(blank=True, null=True, verbose_name='상황판단')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='PSAT')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rank_category', to='a_prime.resultstudent')),
            ],
            options={
                'verbose_name': '[성적확인] 07_직렬 등수',
                'verbose_name_plural': '[성적확인] 07_직렬 등수',
                'db_table': 'a_prime_result_rank_category',
            },
        ),
        migrations.CreateModel(
            name='ResultAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=a_prime.models.choices.answer_choice, default=1, verbose_name='답안')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_answers', to='a_prime.problem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='a_prime.resultstudent')),
            ],
            options={
                'verbose_name': '[성적확인] 03_답안',
                'verbose_name_plural': '[성적확인] 03_답안',
                'db_table': 'a_prime_result_answer',
            },
        ),
        migrations.AddConstraint(
            model_name='problem',
            constraint=models.UniqueConstraint(fields=('psat', 'subject', 'number'), name='unique_prime_problem'),
        ),
        migrations.AddConstraint(
            model_name='resultstudent',
            constraint=models.UniqueConstraint(fields=('psat', 'category', 'name', 'serial'), name='unique_prime_result_student'),
        ),
        migrations.AddConstraint(
            model_name='resultregistry',
            constraint=models.UniqueConstraint(fields=('user', 'student'), name='unique_prime_result_registry'),
        ),
        migrations.AddConstraint(
            model_name='resultanswer',
            constraint=models.UniqueConstraint(fields=('student', 'problem'), name='unique_prime_result_answer'),
        ),
    ]
