# Generated by Django 5.1 on 2024-12-10 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_prime', '0002_alter_resultrankcategory_subject_0_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultanswercount',
            old_name='count_total',
            new_name='count_sum',
        ),
        migrations.RenameField(
            model_name='resultrankcategory',
            old_name='total',
            new_name='sum',
        ),
        migrations.RenameField(
            model_name='resultranktotal',
            old_name='total',
            new_name='sum',
        ),
        migrations.RenameField(
            model_name='resultscore',
            old_name='total',
            new_name='sum',
        ),
        migrations.CreateModel(
            name='ResultAnswerCountLowRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_1', models.IntegerField(default=0, verbose_name='①')),
                ('count_2', models.IntegerField(default=0, verbose_name='②')),
                ('count_3', models.IntegerField(default=0, verbose_name='③')),
                ('count_4', models.IntegerField(default=0, verbose_name='④')),
                ('count_5', models.IntegerField(default=0, verbose_name='⑤')),
                ('count_0', models.IntegerField(default=0, verbose_name='미표기')),
                ('count_multiple', models.IntegerField(default=0, verbose_name='중복표기')),
                ('count_sum', models.IntegerField(default=0, verbose_name='총계')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_answer_count_low_rank', to='a_prime.problem')),
            ],
            options={
                'verbose_name': '[성적확인] 08_답안 개수(하위권)',
                'verbose_name_plural': '[성적확인] 08_답안 개수(하위권)',
                'db_table': 'a_prime_result_answer_count_low_rank',
            },
        ),
        migrations.CreateModel(
            name='ResultAnswerCountMidRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_1', models.IntegerField(default=0, verbose_name='①')),
                ('count_2', models.IntegerField(default=0, verbose_name='②')),
                ('count_3', models.IntegerField(default=0, verbose_name='③')),
                ('count_4', models.IntegerField(default=0, verbose_name='④')),
                ('count_5', models.IntegerField(default=0, verbose_name='⑤')),
                ('count_0', models.IntegerField(default=0, verbose_name='미표기')),
                ('count_multiple', models.IntegerField(default=0, verbose_name='중복표기')),
                ('count_sum', models.IntegerField(default=0, verbose_name='총계')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_answer_count_mid_rank', to='a_prime.problem')),
            ],
            options={
                'verbose_name': '[성적확인] 09_답안 개수(중위권)',
                'verbose_name_plural': '[성적확인] 09_답안 개수(중위권)',
                'db_table': 'a_prime_result_answer_count_mid_rank',
            },
        ),
        migrations.CreateModel(
            name='ResultAnswerCountTopRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_1', models.IntegerField(default=0, verbose_name='①')),
                ('count_2', models.IntegerField(default=0, verbose_name='②')),
                ('count_3', models.IntegerField(default=0, verbose_name='③')),
                ('count_4', models.IntegerField(default=0, verbose_name='④')),
                ('count_5', models.IntegerField(default=0, verbose_name='⑤')),
                ('count_0', models.IntegerField(default=0, verbose_name='미표기')),
                ('count_multiple', models.IntegerField(default=0, verbose_name='중복표기')),
                ('count_sum', models.IntegerField(default=0, verbose_name='총계')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_answer_count_top_rank', to='a_prime.problem')),
            ],
            options={
                'verbose_name': '[성적확인] 10_답안 개수(상위권)',
                'verbose_name_plural': '[성적확인] 10_답안 개수(상위권)',
                'db_table': 'a_prime_result_answer_count_top_rank',
            },
        ),
    ]
