# Generated by Django 5.1 on 2024-12-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_prime', '0003_rename_count_total_resultanswercount_count_sum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultanswercountlowrank',
            options={'verbose_name': '[성적확인] 10_답안 개수(하위권)', 'verbose_name_plural': '[성적확인] 10_답안 개수(하위권)'},
        ),
        migrations.AlterModelOptions(
            name='resultanswercounttoprank',
            options={'verbose_name': '[성적확인] 08_답안 개수(상위권)', 'verbose_name_plural': '[성적확인] 08_답안 개수(상위권)'},
        ),
        migrations.AddField(
            model_name='resultrankcategory',
            name='participants',
            field=models.IntegerField(blank=True, null=True, verbose_name='총 인원'),
        ),
        migrations.AddField(
            model_name='resultranktotal',
            name='participants',
            field=models.IntegerField(blank=True, null=True, verbose_name='총 인원'),
        ),
    ]
