# Generated by Django 5.1 on 2024-12-11 07:51

import a_prime.models.choices
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_prime', '0004_alter_resultanswercountlowrank_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=a_prime.models.choices.statistics_department_choice, default='전체', max_length=40, verbose_name='직렬')),
                ('subject_0', models.JSONField(default=dict, verbose_name='헌법')),
                ('subject_1', models.JSONField(default=dict, verbose_name='언어논리')),
                ('subject_2', models.JSONField(default=dict, verbose_name='자료해석')),
                ('subject_3', models.JSONField(default=dict, verbose_name='상황판단')),
                ('sum', models.JSONField(default=dict, verbose_name='PSAT')),
                ('psat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_statistics', to='a_prime.psat')),
            ],
            options={
                'verbose_name': '[성적확인] 00_시험통계',
                'verbose_name_plural': '[성적확인] 00_시험통계',
                'db_table': 'a_prime_result_statistics',
                'constraints': [models.UniqueConstraint(fields=('psat', 'department'), name='unique_prime_result_statistics')],
            },
        ),
    ]
