# Generated by Django 5.1 on 2024-12-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_prime', '0005_resultstatistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultrankcategory',
            old_name='sum',
            new_name='average',
        ),
        migrations.RenameField(
            model_name='resultranktotal',
            old_name='sum',
            new_name='average',
        ),
        migrations.RenameField(
            model_name='resultstatistics',
            old_name='sum',
            new_name='average',
        ),
    ]
