# Generated by Django 5.1 on 2024-12-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_prime', '0006_rename_sum_resultrankcategory_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultscore',
            name='average',
            field=models.FloatField(blank=True, null=True, verbose_name='PSAT 평균'),
        ),
    ]
