# Generated by Django 5.1 on 2025-01-27 07:48

import a_prime.models.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_prime', '0009_predictanswercountlowrank_answer_predict_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psat',
            name='year',
            field=models.IntegerField(choices=a_prime.models.choices.year_choice, default=2025, verbose_name='연도'),
        ),
    ]
