# Generated by Django 5.0.3 on 2024-07-22 03:45

import a_score.models.base_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primepolicestudent',
            name='selection',
            field=models.CharField(choices=a_score.models.base_settings.ChoiceMethod.police_subject_choices, default='minbeob', max_length=20, verbose_name='선택과목'),
        ),
    ]
