# Generated by Django 5.0.3 on 2024-07-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_score', '0002_primepolicestudent_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='primepoliceanswercount',
            name='all',
            field=models.JSONField(default=dict, verbose_name='전체'),
        ),
        migrations.AddField(
            model_name='primepoliceexam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='primepoliceexam',
            name='participants',
            field=models.JSONField(default=dict, verbose_name='전체 참여자수'),
        ),
        migrations.AddField(
            model_name='primepoliceexam',
            name='statistics',
            field=models.JSONField(default=dict, verbose_name='성적 통계'),
        ),
        migrations.AddField(
            model_name='primepolicestudent',
            name='rank',
            field=models.JSONField(default=dict, verbose_name='등수'),
        ),
        migrations.AddField(
            model_name='primepsatanswercount',
            name='all',
            field=models.JSONField(default=dict, verbose_name='전체'),
        ),
        migrations.AddField(
            model_name='primepsatexam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='primepsatexam',
            name='participants',
            field=models.JSONField(default=dict, verbose_name='전체 참여자수'),
        ),
        migrations.AddField(
            model_name='primepsatexam',
            name='statistics',
            field=models.JSONField(default=dict, verbose_name='성적 통계'),
        ),
        migrations.AddField(
            model_name='primepsatstudent',
            name='rank',
            field=models.JSONField(default=dict, verbose_name='등수'),
        ),
    ]
