# Generated by Django 5.1 on 2025-01-27 07:48

import a_score.models.base_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_score', '0004_primepsatstudent_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primepoliceanswercount',
            name='year',
            field=models.IntegerField(choices=a_score.models.base_settings.ChoiceMethod.year_choices, default=2026, verbose_name='연도'),
        ),
        migrations.AlterField(
            model_name='primepoliceexam',
            name='year',
            field=models.IntegerField(choices=a_score.models.base_settings.ChoiceMethod.year_choices, default=2026, verbose_name='연도'),
        ),
        migrations.AlterField(
            model_name='primepolicestudent',
            name='year',
            field=models.IntegerField(choices=a_score.models.base_settings.ChoiceMethod.year_choices, default=2026, verbose_name='연도'),
        ),
        migrations.AlterField(
            model_name='primepsatanswercount',
            name='year',
            field=models.IntegerField(choices=a_score.models.base_settings.ChoiceMethod.year_choices, default=2025, verbose_name='연도'),
        ),
        migrations.AlterField(
            model_name='primepsatexam',
            name='year',
            field=models.IntegerField(choices=a_score.models.base_settings.ChoiceMethod.year_choices, default=2025, verbose_name='연도'),
        ),
        migrations.AlterField(
            model_name='primepsatstudent',
            name='year',
            field=models.IntegerField(choices=a_score.models.base_settings.ChoiceMethod.year_choices, default=2025, verbose_name='연도'),
        ),
    ]
